# Generated by Django 5.1.2 on 2024-11-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_tipocategoria_categoria_examen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='direccion',
            field=models.CharField(max_length=100, unique=True, verbose_name='Direccion Trabajo'),
        ),
    ]
