# Generated by Django 5.1.2 on 2024-11-21 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_medicamento_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditUser',
        ),
    ]
